// <auto-generated />
using System;
using Foodio.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foodio.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Foodio.API.Models.AudioTour", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("MapImage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("StopsCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Vibe")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("AudioTours");

                    b.HasData(
                        new
                        {
                            Id = "tour_1",
                            Description = "A vibrant nighttime walk through seafood alleys, noodle counters, and quick snack stops.",
                            Duration = "2.5 hrs",
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsTrending = true,
                            Location = "District 1 and District 4 alleys",
                            MapImage = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            Rating = 4.9m,
                            StopsCount = 6,
                            Title = "Midnight Snacking",
                            Vibe = "Energetic"
                        },
                        new
                        {
                            Id = "tour_2",
                            Description = "Fresh shellfish, grilled oysters, and local ordering tips from the canal-side stalls.",
                            Duration = "1.5 hrs",
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsTrending = false,
                            Location = "Vinh Khanh Food Street",
                            MapImage = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            Rating = 4.7m,
                            StopsCount = 4,
                            Title = "Seafood Heaven Tour",
                            Vibe = "Premium"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Seating")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Foodio.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "waves",
                            Name = "Seafood",
                            Slug = "seafood"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "soup",
                            Name = "Noodles",
                            Slug = "noodles"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "store",
                            Name = "Street Food",
                            Slug = "street-food"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "coffee",
                            Name = "Cafe",
                            Slug = "cafe"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ChatThreadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Status")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ChatThreadId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = "msg_1",
                            ChatThreadId = "oc_oanh_thread",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sender = "user",
                            Status = "read",
                            Text = "Hi, do you have a table for 4 tonight around 7 PM?",
                            Timestamp = "4:30 PM"
                        },
                        new
                        {
                            Id = "msg_2",
                            ChatThreadId = "oc_oanh_thread",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sender = "restaurant",
                            Text = "Hello! Yes, we have space. Do you prefer indoor or street-side outdoor seating?",
                            Timestamp = "4:32 PM"
                        },
                        new
                        {
                            Id = "msg_3",
                            ChatThreadId = "oc_oanh_thread",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sender = "restaurant",
                            Text = "Perfect. We will hold an outdoor table for you.",
                            Timestamp = "Just now"
                        },
                        new
                        {
                            Id = "msg_bm25_1",
                            ChatThreadId = "banh_mi_25_thread",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sender = "user",
                            Status = "read",
                            Text = "Do you still have original pate banh mi?",
                            Timestamp = "Yesterday"
                        },
                        new
                        {
                            Id = "msg_bm25_2",
                            ChatThreadId = "banh_mi_25_thread",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Sender = "restaurant",
                            Text = "We are sold out for today, sorry!",
                            Timestamp = "Yesterday"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.ChatThread", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LastMessageText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("LastMessageTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RestaurantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("ChatThreads");

                    b.HasData(
                        new
                        {
                            Id = "oc_oanh_thread",
                            Avatar = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            LastMessageText = "Perfect. We will hold an outdoor table for you.",
                            LastMessageTime = "Now",
                            Name = "Oc Oanh",
                            RestaurantId = "oc_oanh",
                            StatusText = "Usually replies in 5m",
                            UnreadCount = 0
                        },
                        new
                        {
                            Id = "banh_mi_25_thread",
                            Avatar = "https://images.unsplash.com/photo-1608039829572-78524f79c4c7",
                            LastMessageText = "We are sold out for today, sorry!",
                            LastMessageTime = "Yesterday",
                            Name = "Banh Mi 25",
                            RestaurantId = "banh_mi_25",
                            StatusText = "Replies in 1h",
                            UnreadCount = 0
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.CommunityPost", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("bit");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("TimeAgo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("CommunityPosts");

                    b.HasData(
                        new
                        {
                            Id = "post_1",
                            Author = "foodie_explorer",
                            Avatar = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            CommentsCount = 18,
                            Content = "A tiny alley stall with bold seafood flavors and a packed local crowd.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Handle = "@foodie_explorer",
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsLiked = false,
                            IsSaved = false,
                            LikesCount = 245,
                            LocationName = "Oc Dao",
                            Rating = 4.8m,
                            TimeAgo = "2 hours ago"
                        },
                        new
                        {
                            Id = "post_2",
                            Author = "street_bites",
                            Avatar = "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10",
                            CommentsCount = 45,
                            Content = "Rich broth, springy noodles, tight seating, and the right late-night energy.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Handle = "@street_bites",
                            Image = "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10",
                            IsLiked = true,
                            IsSaved = false,
                            LikesCount = 892,
                            LocationName = "Pho Quynh",
                            Rating = 4.0m,
                            TimeAgo = "5 hours ago"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.FoodStreet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenterLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("CenterLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("OpeningWindow")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("FoodStreets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenterLatitude = 10.759245m,
                            CenterLongitude = 106.706566m,
                            Description = "A dense seafood corridor known for snails, grilled shellfish, and canal-side tables.",
                            District = "District 4, Ho Chi Minh City",
                            Name = "Vinh Khanh Food Street",
                            OpeningWindow = "5:00 PM - 12:00 AM"
                        },
                        new
                        {
                            Id = 2,
                            CenterLatitude = 10.767611m,
                            CenterLongitude = 106.693641m,
                            Description = "Late-night noodle shops and quick street snacks near the backpacker quarter.",
                            District = "District 1, Ho Chi Minh City",
                            Name = "Pham Ngu Lao Night Bites",
                            OpeningWindow = "Open late"
                        },
                        new
                        {
                            Id = 3,
                            CenterLatitude = 10.764812m,
                            CenterLongitude = 106.688938m,
                            Description = "Small alley stalls serving seafood, banh mi, and local comfort food.",
                            District = "District 1, Ho Chi Minh City",
                            Name = "Nguyen Trai Alley Eats",
                            OpeningWindow = "10:00 AM - 11:00 PM"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.MenuItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RestaurantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = "dish_1",
                            Description = "Spicy stir-fried crab with rich garlic butter sauce.",
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsAvailable = true,
                            Name = "Garlic Butter Crab",
                            Price = 15.00m,
                            RestaurantId = "oc_dao"
                        },
                        new
                        {
                            Id = "dish_2",
                            Description = "Fresh oysters grilled with scallion oil and toasted peanuts.",
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsAvailable = true,
                            Name = "Grilled Oysters",
                            Price = 12.50m,
                            RestaurantId = "oc_dao"
                        },
                        new
                        {
                            Id = "dish_oanh_1",
                            Description = "Sweet and sour tamarind snails with morning glory.",
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsAvailable = true,
                            Name = "Spicy Tamarind Snails",
                            Price = 8.50m,
                            RestaurantId = "oc_oanh"
                        },
                        new
                        {
                            Id = "dish_pq_1",
                            Description = "Beef pho with rare beef, brisket, tendon, and beef balls.",
                            Image = "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10",
                            IsAvailable = true,
                            Name = "Beef Pho Special",
                            Price = 4.50m,
                            RestaurantId = "pho_quynh"
                        },
                        new
                        {
                            Id = "dish_bm25_1",
                            Description = "Crisp baguette with pate, pork, herbs, pickles, and chili.",
                            Image = "https://images.unsplash.com/photo-1608039829572-78524f79c4c7",
                            IsAvailable = true,
                            Name = "Original Pate Banh Mi",
                            Price = 3.25m,
                            RestaurantId = "banh_mi_25"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.Restaurant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("FoodStreetId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("ReplySpeed")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FoodStreetId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = "oc_dao",
                            Address = "212B Alley, Nguyen Trai Street",
                            Area = "District 1, Ho Chi Minh City",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Distance = "1.2 km away",
                            FoodStreetId = 3,
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsActive = true,
                            IsVerified = true,
                            Latitude = 10.763921m,
                            Longitude = 106.688515m,
                            Name = "Oc Dao",
                            OpeningHours = "10:00 AM - 11:00 PM",
                            PriceRange = "$$$",
                            Rating = 4.8m,
                            ReplySpeed = "Usually replies in 5m"
                        },
                        new
                        {
                            Id = "oc_oanh",
                            Address = "534 Vinh Khanh Street",
                            Area = "District 4, Ho Chi Minh City",
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Distance = "0.5 km away",
                            FoodStreetId = 1,
                            Image = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            IsActive = true,
                            IsVerified = true,
                            Latitude = 10.759031m,
                            Longitude = 106.706962m,
                            Name = "Oc Oanh",
                            OpeningHours = "1:00 PM - 12:00 AM",
                            PriceRange = "$$",
                            Rating = 4.8m,
                            ReplySpeed = "Usually replies in 5m"
                        },
                        new
                        {
                            Id = "pho_quynh",
                            Address = "323 Pham Ngu Lao",
                            Area = "District 1, Ho Chi Minh City",
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Distance = "1.8 km away",
                            FoodStreetId = 2,
                            Image = "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10",
                            IsActive = true,
                            IsVerified = false,
                            Latitude = 10.767836m,
                            Longitude = 106.693385m,
                            Name = "Pho Quynh",
                            OpeningHours = "Open 24/7",
                            PriceRange = "$",
                            Rating = 4.5m,
                            ReplySpeed = "Replies in standard hours"
                        },
                        new
                        {
                            Id = "banh_mi_25",
                            Address = "25 Huynh Khuong Ninh",
                            Area = "District 1, Ho Chi Minh City",
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Distance = "2.0 km away",
                            FoodStreetId = 3,
                            Image = "https://images.unsplash.com/photo-1608039829572-78524f79c4c7",
                            IsActive = true,
                            IsVerified = true,
                            Latitude = 10.791013m,
                            Longitude = 106.695142m,
                            Name = "Banh Mi 25",
                            OpeningHours = "7:00 AM - 9:00 PM",
                            PriceRange = "$",
                            Rating = 4.6m,
                            ReplySpeed = "Replies in 1h"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.RestaurantRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("FoodStreetId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FoodStreetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("RestaurantRequests");
                });

            modelBuilder.Entity("Foodio.API.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("RestaurantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = "rev_1",
                            Author = "Jane Doe",
                            Avatar = "JD",
                            Comment = "Incredible alley spot. The garlic butter sauce is perfect with bread.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            Rating = 5.0m,
                            RestaurantId = "oc_dao",
                            Role = "Local Guide"
                        },
                        new
                        {
                            Id = "rev_2",
                            Author = "Alex Smith",
                            Avatar = "AS",
                            Comment = "Great crab but a bit crowded. Prices are moderate.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 4.0m,
                            RestaurantId = "oc_dao",
                            Role = "Food Traveler"
                        },
                        new
                        {
                            Id = "rev_3",
                            Author = "Nguyen Van A",
                            Avatar = "NV",
                            Comment = "Average snails. The service is nice though.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 3.0m,
                            RestaurantId = "oc_dao",
                            Role = "Street Food Lover"
                        },
                        new
                        {
                            Id = "rev_oanh_1",
                            Author = "Minh Tuan",
                            Avatar = "MT",
                            Comment = "Fast service and a lively street-side seafood atmosphere.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://images.unsplash.com/photo-1559737558-2f5a35f4523b",
                            Rating = 5.0m,
                            RestaurantId = "oc_oanh",
                            Role = "Snail aficionado"
                        },
                        new
                        {
                            Id = "rev_oanh_2",
                            Author = "Tran Binh",
                            Avatar = "TB",
                            Comment = "Lively place. Highly recommend the tamarind sauce snails.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 4.0m,
                            RestaurantId = "oc_oanh",
                            Role = "Snack critic"
                        },
                        new
                        {
                            Id = "rev_pq_1",
                            Author = "An Binh",
                            Avatar = "AB",
                            Comment = "Open all night and very popular near Bui Vien walking street.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10",
                            Rating = 4.0m,
                            RestaurantId = "pho_quynh",
                            Role = "Pho lover"
                        },
                        new
                        {
                            Id = "rev_pq_2",
                            Author = "John C",
                            Avatar = "JC",
                            Comment = "Delicious hot broth, super fresh herbs. Best late night meal!",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10",
                            Rating = 5.0m,
                            RestaurantId = "pho_quynh",
                            Role = "Backpacker"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RestaurantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "usr_1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@foodio.com",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = "usr_2",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "owner@foodio.com",
                            IsActive = true,
                            PasswordHash = "123456",
                            RestaurantId = "oc_dao",
                            Role = "Owner",
                            Username = "owner_ocdao"
                        },
                        new
                        {
                            Id = "usr_3",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "customer@foodio.com",
                            IsActive = true,
                            PasswordHash = "123456",
                            Role = "User",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("Foodio.API.Models.Booking", b =>
                {
                    b.HasOne("Foodio.API.Models.Restaurant", "Restaurant")
                        .WithMany("Bookings")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Foodio.API.Models.ChatMessage", b =>
                {
                    b.HasOne("Foodio.API.Models.ChatThread", "ChatThread")
                        .WithMany("Messages")
                        .HasForeignKey("ChatThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatThread");
                });

            modelBuilder.Entity("Foodio.API.Models.ChatThread", b =>
                {
                    b.HasOne("Foodio.API.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Foodio.API.Models.MenuItem", b =>
                {
                    b.HasOne("Foodio.API.Models.Restaurant", "Restaurant")
                        .WithMany("Dishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Foodio.API.Models.Restaurant", b =>
                {
                    b.HasOne("Foodio.API.Models.Category", "Category")
                        .WithMany("Restaurants")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Foodio.API.Models.FoodStreet", "FoodStreet")
                        .WithMany("Restaurants")
                        .HasForeignKey("FoodStreetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FoodStreet");
                });

            modelBuilder.Entity("Foodio.API.Models.RestaurantRequest", b =>
                {
                    b.HasOne("Foodio.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodio.API.Models.FoodStreet", "FoodStreet")
                        .WithMany()
                        .HasForeignKey("FoodStreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodio.API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FoodStreet");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Foodio.API.Models.Review", b =>
                {
                    b.HasOne("Foodio.API.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Foodio.API.Models.Category", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("Foodio.API.Models.ChatThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Foodio.API.Models.FoodStreet", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("Foodio.API.Models.Restaurant", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Dishes");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
